# CH-DAV
# 13_meteo_nabel

#   NABEL measurements
#
#   Complete year in one respective file
#
#   File has ANSI encoding, see filetype "DAV13-RAW-NABEL-CSV-1MIN-201901010000"
#   for details about ANSI.
#
#   The timestamp is built from the first five columns. This settings file
#   assigns the column names YEAR, MONTH, DAY, HOUR, MINUTE to these columns.
#   pandas can recognizes columns with these names as time columns and
#   timestamp-building is thus easy.
#   Then the columns are combined into the full timestamp using the setting
#   'data_build_timestamp'.
#
#   Similar to DAV13-RAW-NABEL-SSV-TXT-10MIN-200001010000.yaml, but different
#   column order.
#
#   Since these are yearly datafiles, there or not many files and thus filetype_id
#   gives the filenames of all valid files directly without wildcards.


DAV13-RAW-NABEL-SSV-TXT-10MIN-200901010000:
  # SSV: space-separated files
  # First file: DAV_NABEL.10min_2009.01-12.txt
  # Last file:  DAV_NABEL.10min_2012.12.txt
  filetype_valid_from: 2009-01-01 00:00:00
  filetype_valid_to: 2012-12-01 00:00:00
  filetype_id: [ 'DAV_NABEL.10min_2009.01-12.txt', 'DAV_NABEL.10min_2011.11-2012.03.txt',
                 'DAV_NABEL.10min_2012.04-11.txt', 'DAV_NABEL.10min_2012.12.txt' ]
  filetype_dateparser: [ 'DAV_NABEL.10min_%Y.%m-12.txt', 'DAV_NABEL.10min_%Y.%m-2012.03.txt',
                         'DAV_NABEL.10min_%Y.%m-11.txt', 'DAV_NABEL.10min_%Y.%m.txt' ]
  filetype_gzip: false
  filegroup: 13_meteo_nabel
  data_raw_freq: 10T
  # Skip complete upper part, incl. column name info:
  data_skiprows: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21 ]
#  data_skiprows: [ 0 ]
  data_headerrows: 0
#  data_headerrows: [ 0 ]
  data_index_col: -9999
  data_parse_dates: false
  data_date_parser: false
  data_build_timestamp: "YEAR0+MONTH1+DAY2+HOUR3+MINUTE4"
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: cp1252
  data_delimiter: '\s+'
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    YEAR:
    MONTH:
    DAY:
    HOUR:
    MINUTE:
    Temperatur: { field: TA_NABEL_T1_35_1, gain: 1, units: degC, measurement: TA }
    rel. Feuchte: { field: RH_NABEL_T1_35_1, gain: 1, units: "%", measurement: RH }
    Druck: { field: PA_NABEL_H1_2_1, gain: 1, units: hPa, measurement: PA }
    Windrichtung: { field: WD_VANE_NABEL_T1_35_1, gain: 1, units: deg, measurement: WD }
    Windgeschwindigkeit: { field: WS_CUP_NABEL_T1_35_1, gain: 1, units: m s-1, measurement: WS }
    Windspitze: { field: WS_CUP_MAX_NABEL_T1_35_1, gain: 1, units: m s-1, measurement: WS }
    Strahlungsbilanz: { field: NETRAD_NABEL_T1_35_1, gain: 1, units: W m-2, measurement: NETRAD }
    Globalstrahlung: { field: SW_IN_NABEL_T1_35_1, gain: 1, units: W m-2, measurement: SW }
    Niederschlagsmenge: { field: PREC_TOT_NABEL_T1_25_1, gain: 1, units: mm, measurement: PREC }
