# CH-DAV
# 17_meteo_profile


DAV17-RAW-TOA5-PRF-DAT-10S-202201030000:
  # TOA5 format
  # First file: CH-DAV_meteo-profile_20220103.dat (the very first CH-DAV_meteo-profile_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2022-01-03 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-DAV_meteo-profile_*.dat
  filetype_dateparser: CH-DAV_meteo-profile_%Y%m%d.dat
  filetype_gzip: false
  db_bucket: ch-dav_raw
  filegroup: 17_meteo_profile
  data_raw_freq: 10S
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    RH_T1_1_1_Avg: { field: RH_PRF_T1_1_1, units: false, measurement: RH }
    RH_T1_1_1_Std: { field: RH_PRF_SD_T1_1_1, units: false, measurement: _SD }
    RH_T1_2_1_Avg: { field: RH_PRF_T1_2_1, units: false, measurement: RH }
    RH_T1_2_1_Std: { field: RH_PRF_SD_T1_2_1, units: false, measurement: _SD }
    RH_T1_10_1_Avg: { field: RH_PRF_T1_10_1, units: false, measurement: RH }
    RH_T1_10_1_Std: { field: RH_PRF_SD_T1_10_1, units: false, measurement: _SD }
    RH_T1_20_1_Avg: { field: RH_PRF_T1_20_1, units: false, measurement: RH }
    RH_T1_20_1_Std: { field: RH_PRF_SD_T1_20_1, units: false, measurement: _SD }
    RH_T1_25_1_Avg: { field: RH_PRF_T1_25_1, units: false, measurement: RH }
    RH_T1_25_1_Std: { field: RH_PRF_SD_T1_25_1, units: false, measurement: _SD }
    RH_T1_35_1_Avg: { field: RH_PRF_T1_35_1, units: false, measurement: RH }
    RH_T1_35_1_Std: { field: RH_PRF_SD_T1_35_1, units: false, measurement: _SD }
    TA_T1_1_1_Avg: { field: TA_PRF_T1_1_1, units: false, measurement: TA }
    TA_T1_1_1_Std: { field: TA_PRF_SD_T1_1_1, units: false, measurement: _SD }
    TA_T1_2_1_Avg: { field: TA_PRF_T1_2_1, units: false, measurement: TA }
    TA_T1_2_1_Std: { field: TA_PRF_SD_T1_2_1, units: false, measurement: _SD }
    TA_T1_10_1_Avg: { field: TA_PRF_T1_10_1, units: false, measurement: TA }
    TA_T1_10_1_Std: { field: TA_PRF_SD_T1_10_1, units: false, measurement: _SD }
    TA_T1_20_1_Avg: { field: TA_PRF_T1_20_1, units: false, measurement: TA }
    TA_T1_20_1_Std: { field: TA_PRF_SD_T1_20_1, units: false, measurement: _SD }
    TA_T1_25_1_Avg: { field: TA_PRF_T1_25_1, units: false, measurement: TA }
    TA_T1_25_1_Std: { field: TA_PRF_SD_T1_25_1, units: false, measurement: _SD }
    TA_T1_35_1_Avg: { field: TA_PRF_T1_35_1, units: false, measurement: TA }
    TA_T1_35_1_Std: { field: TA_PRF_SD_T1_35_1, units: false, measurement: _SD }
    WD_T1_1_1: { field: WD_PRF_T1_1_1, units: false, measurement: WD }
    WD_T1_2_1: { field: WD_PRF_T1_2_1, units: false, measurement: WD }
    WD_T1_10_1: { field: WD_PRF_T1_10_1, units: false, measurement: WD }
    WD_T1_20_1: { field: WD_PRF_T1_20_1, units: false, measurement: WD }
    WD_T1_25_1: { field: WD_PRF_T1_25_1, units: false, measurement: WD }
    WD_T1_35_1: { field: WD_PRF_T1_35_1, units: false, measurement: WD }
    WS_T1_1_1: { field: WS_PRF_T1_1_1, units: false, measurement: WS }
    WS_T1_2_1: { field: WS_PRF_T1_2_1, units: false, measurement: WS }
    WS_T1_10_1: { field: WS_PRF_T1_10_1, units: false, measurement: WS }
    WS_T1_20_1: { field: WS_PRF_T1_20_1, units: false, measurement: WS }
    WS_T1_25_1: { field: WS_PRF_T1_25_1, units: false, measurement: WS }
    WS_T1_35_1: { field: WS_PRF_T1_35_1, units: false, measurement: WS }

