# CH-DAV
# 12_meteo_forestfloor


DAV12-RAW-FF1-TOA5-DAT-TBL1-10MIN-201802281110:
  # TOA5
  # First file: CH-DAV_iDL_FF1_0_1_TBL1_2018_02_28_1110.dat
  # Last file:  CH-DAV_iDL_FF1_0_1_TBL1_2018_07_18_0010.dat
  # 10MIN time resolution
  # SWC still in m3 m-3, gain 100 applied to convert to %
  filetype_valid_from: 2018-02-28 11:10:00
  filetype_valid_to: 2018-07-18 00:10:00
  filetype_id: CH-DAV_iDL_FF1_0_1_TBL1_*.dat
  filetype_dateparser: CH-DAV_iDL_FF1_0_1_TBL1_%Y_%m_%d_%H%M.dat
  filetype_gzip: false
  filegroup: 12_meteo_forestfloor
  data_raw_freq: 10T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    SENS_HFP_FF1_0x06_1: { field: SENS_HFP_FF1_0.06_1, units: false, measurement: _XXX }
    CAL_FLAG_FF1_0x06_1: { field: CAL_FLAG_FF1_0.06_1, units: false, measurement: _XXX }
    RECORD: { field: RECORD_FF1_0_1, units: false, measurement: _instrumentmetrics }
    SV_LOGGER_FF1_0_1: { field: SV_LOGGER_FF1_0_1, units: false, measurement: _instrumentmetrics }
    T_LOGGER_FF1_0_1: { field: T_LOGGER_FF1_0_1, units: false, measurement: _instrumentmetrics }
    DNTP_LOGGER_FF1_0_1: { field: DNTP_LOGGER_FF1_0_1, units: false, measurement: _instrumentmetrics }
    TS_FF1_0x03_1_Avg: { field: TS_FF1_0.03_1, units: false, measurement: TS }
    TS_FF1_0x05_1_Avg: { field: TS_FF1_0.05_1, units: false, measurement: TS }
    TS_FF1_0x11_1_Avg: { field: TS_FF1_0.11_1, units: false, measurement: TS }
    TS_FF1_0x21_1_Avg: { field: TS_FF1_0.21_1, units: false, measurement: TS }
    TS_FF1_0x50_1_Avg: { field: TS_FF1_0.50_1, units: false, measurement: TS }
    TS_FF1_0x80_1_Avg: { field: TS_FF1_0.80_1, units: false, measurement: TS }
    TS_FF1_0x05_2_Avg: { field: TS_FF1_0.05_2, units: false, measurement: TS }
    SWC_FF1_0x05_1_Avg: { field: SWC_FF1_0.05_1, units: "%", gain: 100, measurement: SWC }
    SWC_FF1_0x10_1_Avg: { field: SWC_FF1_0.10_1, units: "%", gain: 100, measurement: SWC }
    SWC_FF1_0x24_1_Avg: { field: SWC_FF1_0.24_1, units: "%", gain: 100, measurement: SWC }
    SWC_FF1_0x50_1_Avg: { field: SWC_FF1_0.50_1, units: "%", gain: 100, measurement: SWC }
    SWC_FF1_0x84_1_Avg: { field: SWC_FF1_0.84_1, units: "%", gain: 100, measurement: SWC }
    SWC_FF1_0x05_2_Avg: { field: SWC_FF1_0.05_2, units: "%", gain: 100, measurement: SWC }
    G_FF1_0x06_1_Avg: { field: G_FF1_0.06_1, units: W m-2, measurement: G }
    TS_FF1_0x03_1_Std: { field: TS_SD_FF1_0.03_1, units: false, measurement: _SD }
    TS_FF1_0x05_1_Std: { field: TS_SD_FF1_0.05_1, units: false, measurement: _SD }
    TS_FF1_0x11_1_Std: { field: TS_SD_FF1_0.11_1, units: false, measurement: _SD }
    TS_FF1_0x21_1_Std: { field: TS_SD_FF1_0.21_1, units: false, measurement: _SD }
    TS_FF1_0x50_1_Std: { field: TS_SD_FF1_0.50_1, units: false, measurement: _SD }
    TS_FF1_0x80_1_Std: { field: TS_SD_FF1_0.80_1, units: false, measurement: _SD }
    TS_FF1_0x05_2_Std: { field: TS_SD_FF1_0.05_2, units: false, measurement: _SD }
    SWC_FF1_0x05_1_Std: { field: SWC_SD_FF1_0.05_1, units: "%", gain: 100, measurement: _SD }
    SWC_FF1_0x10_1_Std: { field: SWC_SD_FF1_0.10_1, units: "%", gain: 100, measurement: _SD }
    SWC_FF1_0x24_1_Std: { field: SWC_SD_FF1_0.24_1, units: "%", gain: 100, measurement: _SD }
    SWC_FF1_0x50_1_Std: { field: SWC_SD_FF1_0.50_1, units: "%", gain: 100, measurement: _SD }
    SWC_FF1_0x84_1_Std: { field: SWC_SD_FF1_0.84_1, units: "%", gain: 100, measurement: _SD }
    SWC_FF1_0x05_2_Std: { field: SWC_SD_FF1_0.05_2, units: "%", gain: 100, measurement: _SD }
    G_FF1_0x06_1_Std: { field: G_SD_FF1_0.06_1, units: W m-2, measurement: _SD }
