# CH-LAE
# 10_meteo


LAE10-RAW-TOA5-DAT-TBL1-1MIN-201701230926:
  # TOA5
  # First file: CH-LAE_iDL_T1_47_1_TBL1_20170123-0926.dat (the very first CH-LAE_iDL_T1_47_1_TBL1_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2017-01-23 09:26:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-LAE_iDL_T1_47_1_TBL1_*.dat
  filetype_dateparser: CH-LAE_iDL_T1_47_1_TBL1_%Y%m%d-%H%M.dat
  filetype_gzip: false
  filegroup: 10_meteo
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    BV_CR1000_INT_T1_47_1_Avg: { field: BV_CR1000_INT_T1_47_1, units: false, measurement: _instrumentmetrics }
    BV_CR1000_T1_47_1_Avg: { field: BV_CR1000_T1_47_1, units: false, measurement: _instrumentmetrics }
    HEAT_HS50_T1B4_47_1: { field: HEAT_HS50_T1B4_47_1, units: false, measurement: _instrumentmetrics }
    LW_IN_COR_T1_47_1_Avg: { field: LW_IN_COR_T1_47_1, units: false, measurement: LW }
    LW_IN_COR_T1_47_1_Std: { field: LW_IN_COR_SD_T1_47_1, units: false, measurement: _SD }
    LW_IN_T1_47_1_Avg: { field: LW_IN_T1_47_1, units: false, measurement: LW }
    LW_IN_T1_47_1_Std: { field: LW_IN_SD_T1_47_1, units: false, measurement: _SD }
    LW_OUT_COR_T1_47_1_Avg: { field: LW_OUT_COR_T1_47_1, units: false, measurement: LW }
    LW_OUT_COR_T1_47_1_Std: { field: LW_OUT_COR_SD_T1_47_1, units: false, measurement: _SD }
    LW_OUT_T1_47_1_Avg: { field: LW_OUT_T1_47_1, units: false, measurement: LW }
    LW_OUT_T1_47_1_Std: { field: LW_OUT_SD_T1_47_1, units: false, measurement: _SD }
    LW_VIN_T1_47_1_Avg: { field: LW_VIN_T1_47_1, units: false, measurement: LW }
    LW_VOUT_T1_47_1_Avg: { field: LW_VOUT_T1_47_1, units: false, measurement: LW }
    NTP_T1_47_1: { field: NTP_T1_47_1, units: false, measurement: _instrumentmetrics }
    PA_T1_47_1_Avg: { field: PA_T1_47_1, units: false, measurement: PA }
    PA_T1_47_1_Std: { field: PA_SD_T1_47_1, units: false, measurement: _SD }
    PPFD_DIF_T1_47_1_Avg: { field: PPFD_DIF_T1_47_1, units: false, measurement: PPFD }
    PPFD_DIF_T1_47_1_Std: { field: PPFD_DIF_SD_T1_47_1, units: false, measurement: _SD }
    PPFD_IN_T1_47_1_Avg: { field: PPFD_IN_T1_47_1, units: false, measurement: PPFD }
    PPFD_IN_T1_47_1_Std: { field: PPFD_IN_SD_T1_47_1, units: false, measurement: _SD }
    PPFD_IN_T1_47_2_Avg: { field: PPFD_IN_T1_47_2, units: false, measurement: PPFD }
    PPFD_IN_T1_47_2_Std: { field: PPFD_IN_SD_T1_47_2, units: false, measurement: _SD }
    PPFD_OUT_T1_47_1_Avg: { field: PPFD_OUT_T1_47_1, units: false, measurement: PPFD }
    PPFD_OUT_T1_47_1_Std: { field: PPFD_OUT_SD_T1_47_1, units: false, measurement: _SD }
    PPFD_OUT_T1_47_2_Avg: { field: PPFD_OUT_T1_47_2, units: false, measurement: PPFD }
    PPFD_OUT_T1_47_2_Std: { field: PPFD_OUT_SD_T1_47_2, units: false, measurement: _SD }
    PREC_T1_47_1_Std: { field: PREC_SD_T1_47_1, units: false, measurement: _SD }
    PREC_T1_47_1_Tot: { field: PREC_TOT_T1_47_1, units: false, measurement: PREC }
    RECORD: { field: RECORD_X_X_X, units: false, measurement: _instrumentmetrics }
    RH_T1_47_1_Avg: { field: RH_T1_47_1, units: false, measurement: RH }
    RH_T1_47_1_Std: { field: RH_SD_T1_47_1, units: false, measurement: _SD }
    SW_IN_T1_47_1_Avg: { field: SW_IN_T1_47_1, units: false, measurement: SW }
    SW_IN_T1_47_1_Std: { field: SW_IN_SD_T1_47_1, units: false, measurement: _SD }
    SW_OUT_T1_47_1_Avg: { field: SW_OUT_T1_47_1, units: false, measurement: SW }
    SW_OUT_T1_47_1_Std: { field: SW_OUT_SD_T1_47_1, units: false, measurement: _SD }
    SW_VIN_T1_47_1_Avg: { field: SW_VIN_T1_47_1, units: false, measurement: SW }
    SW_VOUT_T1_47_1_Avg: { field: SW_VOUT_T1_47_1, units: false, measurement: SW }
    T_CR1000_T1_47_1_Avg: { field: T_CR1000_T1_47_1, units: false, measurement: _instrumentmetrics }
    T_CR1000_T1_47_1_Std: { field: T_CR1000_SD_T1_47_1, units: false, measurement: _instrumentmetrics }
    T_RAD_T1_47_1_Avg: { field: T_RAD_T1_47_1, units: false, measurement: _instrumentmetrics }
    T_RAD_T1_47_1_Std: { field: T_RAD_SD_T1_47_1, units: false, measurement: _instrumentmetrics }
    TA_T1_47_1_Avg: { field: TA_T1_47_1, units: false, measurement: TA }
    TA_T1_47_1_Std: { field: TA_SD_T1_47_1, units: false, measurement: _SD }
    WS_CUP_SCALAR_T1_47_1_Avg: { field: WS_CUP_SCALAR_T1_47_1, units: false, measurement: WS }
    WS_CUP_SCALAR_T1_47_1_Std: { field: WS_CUP_SCALAR_SD_T1_47_1, units: false, measurement: _SD }
    WS_CUP_SCALAR_T1_47_1_WVc(1): { field: WS_CUP_SCALAR_WVc(1)_T1_47_1, units: false, measurement: WS }
    WS_CUP_SCALAR_T1_47_1_WVc(2): { field: WS_CUP_SCALAR_WVc(2)_T1_47_1, units: false, measurement: WS }
    WS_CUP_SCALAR_T1_47_1_WVc(3): { field: WS_CUP_SCALAR_WVc(3)_T1_47_1, units: false, measurement: WS }
    WS_CUP_SCALAR_T1_47_1_WVc(4): { field: WS_CUP_SCALAR_WVc(4)_T1_47_1, units: false, measurement: WS }
