# CH-DAV
# 40_chambers_ghg


DAV40-RAW-ICOSSEQ-CMB-DAT-1S-20190410:
  # ICOS format, special sequential format
  # Different locations (horizontal var index) are in different rows
  # instead different columns.
  # Chambers
  # Contains IRGA data CO2, H2O
  # First file: CH-Dav_CM_20190410_L10_F03.dat (the very first CH-Dav_CM_*_L10_F03.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2019-04-10 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-Dav_CM_*_L10_F03.dat
  filetype_dateparser: CH-Dav_CM_%Y%m%d_L10_F03.dat
  filetype_gzip: false
  filegroup: 40_chambers_ghg
  data_raw_freq: S
  data_skiprows: [ ]
  data_headerrows: [ 0 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y%m%d%H%M%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    #    0: { field: <<automatic>>, units: false, measurement: XXX }
    CHANNEL_VICI: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    CO2: { field: <<automatic>>, units: XXX, measurement: CO2 }
    FLOW_VOLRATE: { field: <<automatic>>, units: false, measurement: FLOW }
    H2O: { field: <<automatic>>, units: XXX, measurement: H2O }
    INLET: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    INLET_VICI: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    LIMITS: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    LOCATION: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    MOVEMENT: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    OUTLET_VICI: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    PA_CMB: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    PRESS_CELL: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    T_CELL: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    TA_CMB: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
    VALVES: { field: <<automatic>>, units: false, measurement: _instrumentmetrics }
