# CH-DAV
# 11_meteo_hut


DAV11-RAW-TOA5-DAT-TBL3-1H-201812060001:
  # TOA5
  # First file: CH-DAV_iDL_H1_0_1_TBL3_2018_12_06_0001.dat (the very first CH-DAV_iDL_H1_0_1_TBL3_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2018-12-06 00:01:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-DAV_iDL_H1_0_1_TBL3_*.dat
  filetype_dateparser: CH-DAV_iDL_H1_0_1_TBL3_%Y_%m_%d_%H%M.dat
  filetype_gzip: false
  filegroup: 11_meteo_hut
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    RECORD: { field: RECORD_X_X_X, units: false, measurement: _instrumentmetrics }
    P_1_1_1_Tot: { field: PREC_TOT_LOWRES_T1_20_1, units: false, measurement: PREC }
