# CH-DAV
# 15_meteo_snowheight


DAV15-RAW-TOA5-DAT-1MIN-202112020000:
  # TOA5 format
  # First file: CH-DAV_snowheight_20211202.dat (the very first CH-DAV_snowheight_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2021-12-02 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-DAV_snowheight_*.dat
  filetype_dateparser: CH-DAV_snowheight_%Y%m%d.dat
  filetype_gzip: false
  filegroup: 15_meteo_snowheight
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    D_SNOW_M1_1.8_1_Smp: { field: D_SNOW_M1_1.8_1, units: false, measurement: D_SNOW }
    DIAG_iSR50AT_M1_1.8_1_Smp: { field: DIAG_iSR50AT_M1_1.8_1, units: false, measurement: _instrumentmetrics }
    QUALITY_iSR50AT_M1_1.8_1_Smp: { field: QUALITY_iSR50AT_M1_1.8_1, units: false, measurement: _instrumentmetrics }
    TA_M1_1.8_1_Smp: { field: TA_M1_1.8_1, units: false, measurement: TA }
