# EDDYPRO FULL OUTPUT FILE
# 20_ec_fluxes


DAV20-PROC-EDDYPRO-FULL-OUTPUT-CSV-L0-30MIN:
  # EddyPro full output file (general format)
  # First file: -
  # Last file:  -
  filetype_valid_from: 1900-01-01 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: eddypro_*_full_output_*.csv
  filetype_dateparser: false
  filetype_gzip: false
#  db_bucket: test
  db_bucket: ch-dav_processing
  filegroup: 20_ec_fluxes
  data_raw_freq: 30T
  data_skiprows: [ 0 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: -9999
  data_parse_dates: [ [ 'date', '[yyyy-mm-dd]' ], [ 'time', '[HH:MM]' ] ]
  data_date_parser: '%Y-%m-%d %H:%M'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: Level-0
  data_vars:
#    (z-d)/L: { field: (z-d)/L_X_X_X, units: false, measurement: XXX }
#    absolute_limits_hf: { field: absolute_limits_hf_X_X_X, units: false, measurement: XXX }
#    agc_mean: { field: agc_mean_X_X_X, units: false, measurement: XXX }
#    air_density: { field: air_density_X_X_X, units: false, measurement: XXX }
#    air_heat_capacity: { field: air_heat_capacity_X_X_X, units: false, measurement: XXX }
#    air_molar_volume: { field: air_molar_volume_X_X_X, units: false, measurement: XXX }
#    air_p_mean: { field: air_p_mean_X_X_X, units: false, measurement: XXX }
#    air_pressure: { field: air_pressure_X_X_X, units: false, measurement: XXX }
#    air_t_mean: { field: air_t_mean_X_X_X, units: false, measurement: XXX }
#    air_temperature: { field: air_temperature_X_X_X, units: false, measurement: XXX }
#    amplitude_resolution_hf: { field: amplitude_resolution_hf_X_X_X, units: false, measurement: XXX }
#    attack_angle_hf: { field: attack_angle_hf_X_X_X, units: false, measurement: XXX }
#    bowen_ratio: { field: bowen_ratio_X_X_X, units: false, measurement: XXX }
#    co2_def_timelag: { field: co2_def_timelag_X_X_X, units: false, measurement: XXX }
    co2_flux: { field: FC, units: false, measurement: FLUX_EC }
#    co2_mixing_ratio: { field: co2_mixing_ratio_X_X_X, units: false, measurement: XXX }
#    co2_molar_density: { field: co2_molar_density_X_X_X, units: false, measurement: XXX }
#    co2_mole_fraction: { field: co2_mole_fraction_X_X_X, units: false, measurement: XXX }
#    co2_scf: { field: co2_scf_X_X_X, units: false, measurement: XXX }
#    co2_spikes: { field: co2_spikes_X_X_X, units: false, measurement: XXX }
#    co2_strg: { field: co2_strg_X_X_X, units: false, measurement: XXX }
#    co2_time_lag: { field: co2_time_lag_X_X_X, units: false, measurement: XXX }
#    co2_v-adv: { field: co2_v-adv_X_X_X, units: false, measurement: XXX }
#    co2_var: { field: co2_var_X_X_X, units: false, measurement: XXX }
#    cooler_v_mean: { field: cooler_v_mean_X_X_X, units: false, measurement: XXX }
#    data_size_irga75_mean: { field: data_size_irga75_mean_X_X_X, units: false, measurement: XXX }
#    date: { field: date_X_X_X, units: false, measurement: XXX }
#    daytime: { field: daytime_X_X_X, units: false, measurement: XXX }
#    discontinuities_hf: { field: discontinuities_hf_X_X_X, units: false, measurement: XXX }
#    discontinuities_sf: { field: discontinuities_sf_X_X_X, units: false, measurement: XXX }
#    DOY: { field: DOY_X_X_X, units: false, measurement: XXX }
#    drop_out_hf: { field: drop_out_hf_X_X_X, units: false, measurement: XXX }
#    e: { field: e_X_X_X, units: false, measurement: XXX }
#    es: { field: es_X_X_X, units: false, measurement: XXX }
#    ET: { field: ET, units: false, measurement: FLUX_EC }
#    file_records: { field: file_records_X_X_X, units: false, measurement: XXX }
#    ga_diag_code_irga75_mean: { field: ga_diag_code_irga75_mean_X_X_X, units: false, measurement: XXX }
#    h2o_def_timelag: { field: h2o_def_timelag_X_X_X, units: false, measurement: XXX }
    h2o_flux: { field: FH2O, units: false, measurement: FLUX_EC }
#    h2o_mixing_ratio: { field: h2o_mixing_ratio_X_X_X, units: false, measurement: XXX }
#    h2o_molar_density: { field: h2o_molar_density_X_X_X, units: false, measurement: XXX }
#    h2o_mole_fraction: { field: h2o_mole_fraction_X_X_X, units: false, measurement: XXX }
#    h2o_scf: { field: h2o_scf_X_X_X, units: false, measurement: XXX }
#    h2o_spikes: { field: h2o_spikes_X_X_X, units: false, measurement: XXX }
#    h2o_strg: { field: h2o_strg_X_X_X, units: false, measurement: XXX }
#    h2o_time_lag: { field: h2o_time_lag_X_X_X, units: false, measurement: XXX }
#    h2o_v-adv: { field: h2o_v-adv_X_X_X, units: false, measurement: XXX }
#    h2o_var: { field: h2o_var_X_X_X, units: false, measurement: XXX }
    H: { field: H, units: false, measurement: FLUX_EC }
#    H_scf: { field: H_scf_X_X_X, units: false, measurement: XXX }
#    H_strg: { field: H_strg_X_X_X, units: false, measurement: XXX }
#    L: { field: L_X_X_X, units: false, measurement: XXX }
#    LE: { field: LE, units: false, measurement: FLUX_EC }
#    LE_scf: { field: LE_scf_X_X_X, units: false, measurement: XXX }
#    LE_strg: { field: LE_strg_X_X_X, units: false, measurement: XXX }
#    max_wind_speed: { field: max_wind_speed_X_X_X, units: false, measurement: XXX }
#    model: { field: model_X_X_X, units: false, measurement: XXX }
#    non_steady_wind_hf: { field: non_steady_wind_hf_X_X_X, units: false, measurement: XXX }
#    pitch: { field: pitch_X_X_X, units: false, measurement: XXX }
#    qc_co2_flux: { field: qc_co2_flux_X_X_X, units: false, measurement: XXX }
#    qc_h2o_flux: { field: qc_h2o_flux_X_X_X, units: false, measurement: XXX }
#    qc_H: { field: qc_H_X_X_X, units: false, measurement: XXX }
#    qc_LE: { field: qc_LE_X_X_X, units: false, measurement: XXX }
#    qc_Tau: { field: qc_Tau_X_X_X, units: false, measurement: XXX }
#    rand_err_co2_flux: { field: rand_err_co2_flux_X_X_X, units: false, measurement: XXX }
#    rand_err_h2o_flux: { field: rand_err_h2o_flux_X_X_X, units: false, measurement: XXX }
#    rand_err_H: { field: rand_err_H_X_X_X, units: false, measurement: XXX }
#    rand_err_LE: { field: rand_err_LE_X_X_X, units: false, measurement: XXX }
#    rand_err_Tau: { field: rand_err_Tau_X_X_X, units: false, measurement: XXX }
#    RH: { field: RH_X_X_X, units: false, measurement: XXX }
#    roll: { field: roll_X_X_X, units: false, measurement: XXX }
#    skewness_kurtosis_hf: { field: skewness_kurtosis_hf_X_X_X, units: false, measurement: XXX }
#    skewness_kurtosis_sf: { field: skewness_kurtosis_sf_X_X_X, units: false, measurement: XXX }
#    sonic_temperature: { field: sonic_temperature_X_X_X, units: false, measurement: XXX }
#    specific_humidity: { field: specific_humidity_X_X_X, units: false, measurement: XXX }
#    spikes_hf: { field: spikes_hf_X_X_X, units: false, measurement: XXX }
#    status_code_irga75_mean: { field: status_code_irga75_mean_X_X_X, units: false, measurement: XXX }
#    T*: { field: T*_X_X_X, units: false, measurement: XXX }
#    Tau: { field: Tau_X_X_X, units: false, measurement: XXX }
#    Tau_scf: { field: Tau_scf_X_X_X, units: false, measurement: XXX }
#    Tdew: { field: Tdew_X_X_X, units: false, measurement: XXX }
#    time: { field: time_X_X_X, units: false, measurement: XXX }
#    timelag_hf: { field: timelag_hf_X_X_X, units: false, measurement: XXX }
#    timelag_sf: { field: timelag_sf_X_X_X, units: false, measurement: XXX }
#    TKE: { field: TKE_X_X_X, units: false, measurement: XXX }
#    ts_spikes: { field: ts_spikes_X_X_X, units: false, measurement: XXX }
#    ts_var: { field: ts_var_X_X_X, units: false, measurement: XXX }
#    u*: { field: USTAR, units: false, measurement: WIND_EC }
#    u_rot: { field: U_ROT, units: false, measurement: WIND_EC }
#    u_spikes: { field: U_SPIKES, units: false, measurement: WIND_EC }
#    u_unrot: { field: U_UNROT, units: false, measurement: WIND_EC }
#    u_var: { field: U_VAR, units: false, measurement: WIND_EC }
#    un_co2_flux: { field: FC_UNCORR, units: false, measurement: FLUX_EC }
#    un_h2o_flux: { field: FH2O_UNCORR, units: false, measurement: FLUX_EC }
#    un_H: { field: H_UNCORR, units: false, measurement: FLUX_EC }
#    un_LE: { field: LE_UNCORR, units: false, measurement: FLUX_EC }
#    un_Tau: { field: un_Tau_X_X_X, units: false, measurement: XXX }
#    used_records: { field: used_records_X_X_X, units: false, measurement: XXX }
#    v_rot: { field: v_rot_X_X_X, units: false, measurement: XXX }
#    v_spikes: { field: v_spikes_X_X_X, units: false, measurement: XXX }
#    v_unrot: { field: v_unrot_X_X_X, units: false, measurement: XXX }
#    v_var: { field: v_var_X_X_X, units: false, measurement: XXX }
#    VPD: { field: VPD_X_X_X, units: false, measurement: XXX }
#    w/co2_cov: { field: w/co2_cov_X_X_X, units: false, measurement: XXX }
#    w/h2o_cov: { field: w/h2o_cov_X_X_X, units: false, measurement: XXX }
#    w/ts_cov: { field: w/ts_cov_X_X_X, units: false, measurement: XXX }
#    w_rot: { field: w_rot_X_X_X, units: false, measurement: XXX }
#    w_spikes: { field: w_spikes_X_X_X, units: false, measurement: XXX }
#    w_unrot: { field: w_unrot_X_X_X, units: false, measurement: XXX }
#    w_var: { field: w_var_X_X_X, units: false, measurement: XXX }
#    water_vapor_density: { field: water_vapor_density_X_X_X, units: false, measurement: XXX }
#    wind_dir: { field: WD, units: false, measurement: WIND_EC }
#    wind_speed: { field: WS, units: false, measurement: WIND_EC }
#    x_10%: { field: FETCH_10, units: false, measurement: FOOTPRINT_EC }
#    x_30%: { field: FETCH_30, units: false, measurement: FOOTPRINT_EC }
#    x_50%: { field: FETCH_50, units: false, measurement: FOOTPRINT_EC }
#    x_70%: { field: FETCH_70, units: false, measurement: FOOTPRINT_EC }
#    x_90%: { field: FETCH_90, units: false, measurement: FOOTPRINT_EC }
#    x_offset: { field: FETCH_OFFSET, units: false, measurement: FOOTPRINT_EC }
#    x_peak: { field: FETCH_MAX, units: false, measurement: FOOTPRINT_EC }
#    yaw: { field: yaw_X_X_X, units: false, measurement: XXX }


