# CH-DAV
# 10_meteo


DAV10-RAW-TOA5-DAT-10S-202112020000:
  # TOA5
  # Ambient pressure data
  # First file: CH-DAV_pressure_20211202.dat (the very first CH-DAV_pressure_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2021-12-02 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-DAV_pressure_*.dat
  filetype_dateparser: CH-DAV_pressure_%Y%m%d.dat
  filetype_gzip: false
  db_bucket: ch-dav_raw
  filegroup: 10_meteo
  data_raw_freq: 10S
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    PA_H1_0_1_Avg: { field: PA_H1_0_1, units: false, measurement: PA }
    PA_H1_0_1_Std: { field: PA_SD_H1_0_1, units: false, measurement: _SD }
    PA_T1_35_1_Avg: { field: PA_T1_35_1, units: false, measurement: PA }
    PA_T1_35_1_Std: { field: PA_SD_T1_35_1, units: false, measurement: _SD }
